=== AndSt/MolSim/InputSpheres.xsd
<?xml version="1.0"?>
<xs:schema 
xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<!-- definition of small complex types -->
	<xs:complexType name="centerPos_t">
			<xs:annotation>
			  <xs:documentation>
				The ori_t type consists of a set of 3 coordinates of the origin vector.
				The origin vector points at the lower left corner of the cuboid.
			  </xs:documentation>
			</xs:annotation>
		<xs:sequence>
			<xs:element name="x" type="xs:decimal"/>
			<xs:element name="y" type="xs:decimal"/>
			<xs:element name="z" type="xs:decimal"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="startVel_t">
			<xs:annotation>
			  <xs:documentation>
				The startVel_t type consists of a set of 3 coordinates of start velocity.
				Each particle in the cuboid has the same start velocity (before adding the brownian factor).
			  </xs:documentation>
			</xs:annotation>
		<xs:sequence>
			<xs:element name="vX" type="xs:decimal"/>
			<xs:element name="vY" type="xs:decimal"/>
			<xs:element name="vZ" type="xs:decimal"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="sphere_t">
			<xs:annotation>
			  <xs:documentation>
				The sphere_t type consists of all properties of a sphere.
			  </xs:documentation>
			</xs:annotation>
		<xs:sequence>
			<xs:element name="meshWidthS" type="xs:decimal"/>
			<xs:element name="massS" type="xs:decimal"/>
			<xs:element name="meanVS" type="xs:decimal"/>
			<xs:element name="parTypeS" type="xs:int"/>
			<xs:element name="radiussph" type="xs:int"/>
			<xs:element name="epsilon" type="xs:decimal"/>
			<xs:element name="sigma" type="xs:decimal"/>
			<xs:element name="centerPos" type="centerPos_t"/>
			<xs:element name="startVel" type="startVel_t"/>
		</xs:sequence>
	</xs:complexType>

	<!-- type of the biggest complex element -->
	<xs:complexType name="spheres_t">
			<xs:annotation>
			  <xs:documentation>
				The spheres_t type consists of a list of spheres.
			  </xs:documentation>
			</xs:annotation>
		<xs:sequence>
			<xs:element name="sphere" type="sphere_t" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<!-- definition of the biggest complex element -->
	<xs:element name="spheres" type="spheres_t"/>

</xs:schema>

=== AndSt/MolSim/FallingDropSphere.xml
<?xml version="1.0"?>

<spheres
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="InputSpheres.xsd">

	<sphere>
		<meshWidthS>1.2</meshWidthS>
		<massS>1.0</massS>
		<meanVS>0.1</meanVS>
		<parTypeS>1</parTypeS>
		<radiussph>20</radiussph>
		<epsilon>1.0</epsilon>
		<sigma>1.0</sigma>
		
		<centerPos>
			<x>150.0</x>
			<y>150.0</y>
			<z>0.0</z>
		</centerPos>
		<startVel>
			<vX>0.0</vX>
			<vY>0.0</vY>
			<vZ>0.0</vZ>
		</startVel>		
	</sphere>

</spheres>

=== AndSt/MolSim/InputSpheres.xml
<?xml version="1.0"?>

<spheres
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="InputSpheres.xsd">

	<meshWidthS>1.1225</meshWidthS>
	<massS>1.0</massS>
	<meanVS>0.1</meanVS>
	
	<sphere>
		<parTypeS>1</parTypeS>
		<radiussph>10</radiussph>
		<centerPos>
			<x>30.0</x>
			<y>150.0</y>
			<z>0.0</z>
		</centerPos>
		<startVel>
			<vX>0.0</vX>
			<vY>0.0</vY>
			<vZ>0.0</vZ>
		</startVel>		
	</sphere>

</spheres>
