=== AndSt/MolSim/InputSetting.xsd
<?xml version="1.0"?>
<xs:schema 
xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<!-- definition of small complex types -->
	<xs:complexType name="ljf_t">
			<xs:annotation>
			  <xs:documentation>
				The ljf_t (Lennard-Jones Force) type consists of a set of 2 constants epsilon and sigma.
			  </xs:documentation>
			</xs:annotation>
		<xs:sequence>
			<xs:element name="epsilon" type="xs:decimal"/>
			<xs:element name="sigma" type="xs:decimal"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="lc_t">
			<xs:annotation>
			  <xs:documentation>
				The lc_t (Linked Cell Algorithm) type consists of domain size (3D vector), cutoff radius 
				and boundary condtions ("outflow" or "reflecting").
			  </xs:documentation>
			</xs:annotation>
		<xs:sequence>
			<xs:element name="domainsize" type="domainsize_t"/>
			<xs:element name="rcutoff" type="xs:decimal"/>
			<xs:element name="condition" type="condition_t" maxOccurs="6" minOccurs="6"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="domainsize_t">
			<xs:annotation>
			  <xs:documentation>
				The domainsize_t type consists of 3 coordinates of the diagonally right upper corner of the domain.
				The other opposite corner is (0, 0, 0).
			  </xs:documentation>
			</xs:annotation>
		<xs:sequence>
			<xs:element name="domainX" type="xs:decimal"/>
			<xs:element name="domainY" type="xs:decimal"/>
			<xs:element name="domainZ" type="xs:decimal"/>
		</xs:sequence>
	</xs:complexType>

	<xs:simpleType name="condition_t">
			<xs:annotation>
			  <xs:documentation>
				The condition_t type is an enumeration 
				consisting of "outflow" (1) or "reflecting" (2).
				Each value gives the type of boundary condition we should apply.
			  </xs:documentation>
			</xs:annotation>
		<xs:restriction base="xs:int">
			<xs:enumeration value="1"/>
			<xs:enumeration value="2"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="inputfile_t">
			<xs:annotation>
			  <xs:documentation>
				The inputfile_t type consists of the name of the input file, which gives information of cuboids/particles etc.
				Type = cuboids, particle,...
			  </xs:documentation>
			</xs:annotation>
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="type" type="type_t"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:simpleType name="type_t">
			<xs:annotation>
			  <xs:documentation>
				The type_t type is an enumeration consisting of "cuboids", "particles" and "spheres".
				Each value gives the type of objects we should deal with.
			  </xs:documentation>
			</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="cuboids"/>
			<xs:enumeration value="particles"/>
			<xs:enumeration value="spheres"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:complexType name="outputfile_t">
			<xs:annotation>
			  <xs:documentation>
				The output_file type consists of the base name of vtk output files and their frequency.
				freq = n: An output file will be exported every n time-iterations.
			  </xs:documentation>
			</xs:annotation>
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="freq" type="xs:short"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="thermo_t">
			<xs:annotation>
			  <xs:documentation>
				The thermo type consists of all information needed for a thermostat.
				Also contains brownian_flag (true means the Brownian Motion should be applied).
			  </xs:documentation>
			</xs:annotation>
		<xs:sequence>
			<xs:element name="brownianFlag" type="xs:boolean"/>
			<xs:element name="initT" type="xs:decimal"/>
			<xs:element name="targetT" type="xs:decimal"/>
			<xs:element name="deltaT" type="xs:decimal"/>
			<xs:element name="nThermo" type="xs:int"/>
			<xs:element name="nDelta" type="xs:int"/>
		</xs:sequence>
	</xs:complexType>

	<!-- type of the biggest complex element -->
	<xs:complexType name="pse_t">
			<xs:annotation>
			  <xs:documentation>
				The pse_t type consists of all information needed for a simple simulation.
			  </xs:documentation>
			</xs:annotation>
		<xs:sequence>
			<xs:element name="start_time" type="xs:decimal"/>
			<xs:element name="t_end" type="xs:decimal"/>
			<xs:element name="delta_t" type="xs:decimal"/>
			<xs:element name="ljf" type="ljf_t"/>
			<xs:element name="lc" type="lc_t"/>
			<xs:element name="thermo" type="thermo_t"/>
			<xs:element name="inputfile" type="inputfile_t" maxOccurs="unbounded"/>
			<xs:element name="outputfile" type="outputfile_t"/>
		</xs:sequence>
	</xs:complexType>
	
	<!-- definition of the biggest complex element -->
	<xs:element name="pse" type="pse_t"/>

</xs:schema>

=== AndSt/MolSim/InputSetting.xml
<?xml version="1.0"?>
<pse
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="InputSetting.xsd">

	<start_time>0.0</start_time>
	<t_end>0.1</t_end>
	<delta_t>0.0005</delta_t>
	<numberOfTypes>2</numberOfTypes>
	
	<gconst>-12.44</gconst>
	
	<!-- Short range, linked cell algorithm -->
	<lc>
		<domainsize>
			<domainX>60.0</domainX>
			<domainY>180.0</domainY>
			<domainZ>0.0</domainZ>
		</domainsize>
		<rcutoff>3.0</rcutoff>
	
		<!-- 1=outflow, 2=reflecting for 6 boundaries -->
		<!-- left side -->
		<condition>2</condition>

		<!-- right -->
		<condition>2</condition>

		<!-- ground -->
		<condition>2</condition>

		<!-- upper -->
		<condition>1</condition>

		<!-- front -->
		<condition>2</condition>

		<!-- behind -->
		<condition>2</condition>
	</lc>	
	
	<!-- Thermostats -->
	<thermo>
		<enabled>false</enabled>
		<brownianFlag>true</brownianFlag>
		<initT>0.5</initT>
		<targetT>80</targetT>
		<deltaT>0</deltaT>
		<nThermo>1000</nThermo>
		<nDelta>40000</nDelta>
	</thermo>

	<inputfile>
		<name>InputCuboids.xml</name>
		<!-- particles/cuboids/spheres -->
		<type>cuboids</type>
	</inputfile>
	
	<inputfile>
		<name>InputSpheres.xml</name>
		<!-- particles/cuboids/spheres -->
		<type>spheres</type>
	</inputfile>
	
	<outputfile>
		<name>MolSimVTK</name>
		<freq>10</freq>
	</outputfile>
</pse>

=== AndSt/MolSim/input/CoolingArgonInitSetting.xml
<?xml version="1.0"?>
<pse
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="InputSetting.xsd">

	<start_time>0.0</start_time>
	<t_end>150</t_end>
	<delta_t>0.001</delta_t>
	<numberOfTypes>1</numberOfTypes>
	
	<gconst>0.0</gconst>
	
	<!-- true: smoothed LJ, false: LJ -->
	<force>true</force>
		
	<!-- Short range, linked cell algorithm -->
	<lc>
		<domainsize>
			<domainX>9.2</domainX>
			<domainY>9.2</domainY>
			<domainZ>9.2</domainZ>
		</domainsize>
		<rcutoff>2.3</rcutoff>
	
		<!-- 1=outflow, 2=reflecting for 6 boundaries -->
		<!-- left side -->
		<condition>2</condition>

		<!-- right -->
		<condition>2</condition>

		<!-- ground -->
		<condition>2</condition>

		<!-- upper -->
		<condition>1</condition>

		<!-- front -->
		<condition>2</condition>

		<!-- behind -->
		<condition>2</condition>
	</lc>	
	
	<!-- Thermostats -->
	<thermo>
		<enabled>true</enabled>
		<brownianFlag>false</brownianFlag>
		<initT>0.01</initT>
		<targetT>3.0</targetT>
		<deltaT>0.001</deltaT>
		<nThermo>40</nThermo>
		<nDelta>40</nDelta>
	</thermo>

	<inputfile>
		<name>input/CoolingArgonLiquidCuboid.xml</name>
		<!-- particles/cuboids/spheres -->
		<type>cuboids</type>
	</inputfile>
	
	<outputfile>
		<name>CoolingArgonInit</name>
		<freq>10</freq>
	</outputfile>
</pse>

=== AndSt/MolSim/input/RayleighTaylor3DSetting.xml
<?xml version="1.0"?>
<pse
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="InputSetting.xsd">

	<start_time>0.0</start_time>
	<t_end>100</t_end>
	<delta_t>0.0005</delta_t>
	<numberOfTypes>2</numberOfTypes>
	
	<gconst>-12.44</gconst>
	
	<!-- Short range, linked cell algorithm -->
	<lc>
		<domainsize>
			<domainX>60.0</domainX>
			<domainY>24.0</domainY>
			<domainZ>51.0</domainZ>
		</domainsize>
		<rcutoff>3.0</rcutoff>
	
		<!-- 1=outflow, 2=reflecting, 3=periodic for 6 boundaries -->
		<!-- left side -->
		<condition>3</condition>

		<!-- right -->
		<condition>3</condition>

		<!-- ground -->
		<condition>2</condition>

		<!-- upper -->
		<condition>2</condition>

		<!-- front -->
		<condition>3</condition>

		<!-- behind -->
		<condition>3</condition>
	</lc>	
	
	<!-- Thermostats -->
	<thermo>
		<enabled>true</enabled>
		<brownianFlag>false</brownianFlag>
		<initT>40.0</initT>
		<targetT>80</targetT>
		<deltaT>0</deltaT>
		<nThermo>1000</nThermo>
		<nDelta>200001</nDelta>
	</thermo>

	<inputfile>
		<name>input/RayleighTaylor3DCuboids.xml</name>
		<!-- particles/cuboids/spheres -->
		<type>cuboids</type>
	</inputfile>
		
	<outputfile>
		<name>RayTay3DVTK</name>
		<freq>10</freq>
	</outputfile>
</pse>

=== AndSt/MolSim/input/MembraneSetting.xml
<?xml version="1.0"?>
<pse
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="InputSetting.xsd">

	<start_time>0.0</start_time>
	<t_end>500</t_end>
	<delta_t>0.01</delta_t>
	<numberOfTypes>1</numberOfTypes>
	
	<gconst>-0.001</gconst>
	
	<!-- true: smoothed LJ, false: LJ -->
	<force>false</force>
		
	<!-- Short range, linked cell algorithm -->
	<lc>
		<domainsize>
			<domainX>148.0</domainX>
			<domainY>148.0</domainY>
			<domainZ>148.0</domainZ>
		</domainsize>
		<rcutoff>4.0</rcutoff>
	
		<!-- 1=outflow, 2=reflecting, 3=periodic for 6 boundaries -->
		<!-- left side -->
		<condition>3</condition>

		<!-- right -->
		<condition>3</condition>

		<!-- ground -->
		<condition>3</condition>

		<!-- upper -->
		<condition>3</condition>

		<!-- front -->
		<condition>2</condition>

		<!-- behind -->
		<condition>3</condition>
	</lc>	
	
	<!-- Thermostats -->
	<thermo>
		<enabled>false</enabled>
		<brownianFlag>true</brownianFlag>
		<initT>0.5</initT>
		<targetT>80</targetT>
		<deltaT>0</deltaT>
		<nThermo>1000</nThermo>
		<nDelta>40000</nDelta>
	</thermo>

	<inputfile>
		<name>input/MembraneCuboid.xml</name>
		<!-- particles/cuboids/spheres -->
		<type>cuboids</type>
	</inputfile>
	
	<outputfile>
		<name>MembraneVTK</name>
		<freq>10</freq>
	</outputfile>
</pse>
