=== AndSt/MolSim/input/cxx/tree/cuboids/InputCuboids.xsd
<?xml version="1.0"?>
<xs:schema 
xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<!-- definition of small complex types -->
	<xs:complexType name="ori_t">
			<xs:annotation>
			  <xs:documentation>
				The ori_t type consists of a set of 3 coordinates of the origin vector.
				The origin vector points at the lower left corner of the cuboid.
			  </xs:documentation>
			</xs:annotation>
		<xs:sequence>
			<xs:element name="oriX" type="xs:decimal"/>
			<xs:element name="oriY" type="xs:decimal"/>
			<xs:element name="oriZ" type="xs:decimal"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="startV_t">
			<xs:annotation>
			  <xs:documentation>
				The startV_t type consists of a set of 3 coordinates of start velocity.
				Each particle in the cuboid has the same start velocity (before adding the brownian factor).
			  </xs:documentation>
			</xs:annotation>
		<xs:sequence>
			<xs:element name="velX" type="xs:decimal"/>
			<xs:element name="velY" type="xs:decimal"/>
			<xs:element name="velZ" type="xs:decimal"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="size3D_t">
			<xs:annotation>
			  <xs:documentation>
				The size3D_t type consists of a set of 3 variables width, height and depth of a cuboid.
			  </xs:documentation>
			</xs:annotation>
		<xs:sequence>
			<xs:element name="width" type="xs:int"/>
			<xs:element name="height" type="xs:int"/>
			<xs:element name="depth" type="xs:int"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="cuboid_t">
			<xs:annotation>
			  <xs:documentation>
				The cuboid_t type consists of a set of properties of a cuboid.
			  </xs:documentation>
			</xs:annotation>
		<xs:sequence>
			<xs:element name="meshWidth" type="xs:decimal"/>
			<xs:element name="mass" type="xs:decimal"/>
			<xs:element name="meanV" type="xs:decimal"/>
			<xs:element name="parTypeC" type="xs:int"/>
			<xs:element name="epsilon" type="xs:decimal"/>
			<xs:element name="sigma" type="xs:decimal"/>
			<xs:element name="originVector" type="ori_t"/>
			<xs:element name="startVelocity" type="startV_t"/>
			<xs:element name="size3D" type="size3D_t"/>
		</xs:sequence>
	</xs:complexType>

	<!-- type of the biggest complex element -->
	<xs:complexType name="cuboids_t">
			<xs:annotation>
			  <xs:documentation>
				The cuboids_t type consists of a list of cuboids.
			  </xs:documentation>
			</xs:annotation>
		<xs:sequence>
			<xs:element name="cuboid" type="cuboid_t" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<!-- definition of the biggest complex element -->
	<xs:element name="cuboids" type="cuboids_t"/>

</xs:schema>

=== AndSt/MolSim/RayleighTaylorSmallCuboids.xml
<?xml version="1.0"?>

<cuboids
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="InputCuboids.xsd">
	
	<cuboid>
		<meshWidth>1.2</meshWidth>
		<mass>1.0</mass>
		<meanV>0.1</meanV>
		<parTypeC>0</parTypeC>
		 
		<epsilon>1.0</epsilon>
		<sigma>1.0</sigma>		
		
		<originVector>
			<oriX>0.6</oriX>
			<oriY>2.0</oriY>
			<oriZ>0.0</oriZ>
		</originVector>
		<startVelocity>
			<velX>0.0</velX>
			<velY>0.0</velY>
			<velZ>0.0</velZ>
		</startVelocity>
		<size3D>
			<width>50</width>
			<height>14</height>
			<depth>1</depth>
		</size3D>
	</cuboid>	
	
	<cuboid>
		<meshWidth>1.2</meshWidth>
		<mass>2.0</mass>
		<meanV>0.1</meanV>
		<parTypeC>1</parTypeC>
		 
		<epsilon>1.0</epsilon>
		<sigma>0.9412</sigma>		
		
		<originVector>
			<oriX>0.6</oriX>
			<oriY>19</oriY>
			<oriZ>0.0</oriZ>
		</originVector>
		<startVelocity>
			<velX>0.0</velX>
			<velY>0.0</velY>
			<velZ>0.0</velZ>
		</startVelocity>
		<size3D>
			<width>50</width>
			<height>14</height>
			<depth>1</depth>
		</size3D>
	</cuboid>
</cuboids>

=== AndSt/MolSim/InputCuboids.xml
<?xml version="1.0"?>

<cuboids
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="InputCuboids.xsd">

	<meshWidth>1.1225</meshWidth>
	<mass>1.0</mass>
	<meanV>0.1</meanV>

	<cuboid>
		<originVector>
			<oriX>1.5</oriX>
			<oriY>2.0</oriY>
			<oriZ>0.0</oriZ>
		</originVector>
		<startVelocity>
			<velX>0.0</velX>
			<velY>0.0</velY>
			<velZ>0.0</velZ>
		</startVelocity>
		<size3D>
			<width>250</width>
			<height>50</height>
			<depth>1</depth>
		</size3D>		
	</cuboid>	
</cuboids>
